# -*- coding: utf-8 -*-
"""escape character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H8fxaKR9Y7lD3zeYC_1Pj1t8s_5THXzg
"""

print('Dia berkata:"Pergilah!"')

print ("Aku menimpali: \"Apakahkau ingin aku 'angkat kaki'?!\"")

print (" \\(^_^) / (\\-_-/)")