# -*- coding: utf-8 -*-
"""Manipulasi string.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oMbGNZQn8_08g7TtB-M7Lr9vMgXpZO7j

**string**
"""

nama = 'Azizah Syandia'
asal = "Indonesia"

print(nama)

print(asal)

print(nama, asal)

print(nama + asal)

print("Halo, nama saya")

print("Halo, nama saya",nama,"asal saya dari",asal)

data_lengkap = nama + asal

print(data_lengkap)

"""**String + non string**"""

asal_kota = "Bandar Lampung"
Kode_pos = 35144

asal_kota_kode_pos = asal_kota + str(Kode_pos)

print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3

print(asal_kota_x3)