# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16zkyu0brixrGeN0e61r2L2f8BU35cqNs
"""

template = 'Halo, saya %s dari %s'
print(template % ('Khasia', 'Indonesia'))

template_

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama = 'Khasia', asal = 'Indonesia'))
print(template_2.format('nasi', 'air'))

alamat = 'Surabaya, Jawa Timur, Indonesia'
print(alamat.split())

print('halo selamat pagi!'.upper())

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

print('Indonesia adalah negara kepulauan'.swapcase())
print('Aku cinta negeriku'.swapcase())

angka = '12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', 'tuy'))

paragraf = 'baru baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'kata "di" muncul sebanyak {x} kali')

