# -*- coding: utf-8 -*-
"""UTS compro 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fb8Ayp5neQOazWlmYgWpDrCjVO2CuJ8Q
"""

#menyiapkan data awal sesuai intruksi di soal
raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

#.1.data split
#.1a.memecah string menjadi 2 transaksi berdasarkan titik koma (;)
transaksi_list = raw_log.split(";")
transaksi_1_raw = transaksi_list[0]
transaksi_2_raw = transaksi_list[1]

#.b.memecah masing-masing transaksi berdasarkan tanda pagar (#)
t1_attrs = transaksi_1_raw.split("#")
t2_attrs = transaksi_2_raw.split("#")

#.2 dan 3,advanced cleaning,transformasi dan casting
#.transaksi 1 (kopi susu gula aren)
#.membersihkan label, menghapus spasi dengan split(), dan ubah ke title case
t1_nama = t1_attrs[1].replace("NAMA:", "").strip().title()

#membersiihkan label lalu dicasting menjadi integer(int)
t1_qty = int(t1_attrs[2].replace("QTY:", "").strip())
t1_price = int(t1_attrs[3].replace("PRICE:", "").strip()) s

#transaksi 2 (coffe latte)
#membersihkan label menghapus spasi dengan spliy() dan ubah ke title case
t2_nama = t2_attrs[1].replace("NAMA:", "").strip().title()

#membersihkan label lalu dicasting menjadi integer (int)
t2_qty = int(t2_attrs[2].replace("QTY:", "").strip())
t2_price = int(t2_attrs[3].replace("PRICE:", "").strip())

#perhitungan aritmatika
#.a.menghitung masing masing transaksi
subtotal_1 = t1_qty * t1_price
subtotal_2 = t2_qty * t2_price

#.b.menghitung total pendapatan harian
total_pendapatan = subtotal_1 + subtotal_2

#.5.output laporan F-String
# mengatur f-string utuk lebar kolom dan menambahkan frame
print("=" * 60)
print(f"{'LAPORAN HARIAN KEDAI SOU SPACE':^60}")
print("=" * 60)
print(f"{'MENU':<28}{'QTY':<8}{'HARGA':<12}{'SUBTOTAL'}")
print("-" * 60)
print(f"{t1_nama:<28}{t1_qty:<8}{t1_price:<12}{subtotal_1}")
print(f"{t2_nama:<28}{t2_qty:<8}{t2_price:<12}{subtotal_2}")
print("-" * 60)
print(f"{'TOTAL PENDAPATAN HARI INI':<32}Rp {total_pendapatan}")
print("=" * 60)

"""PENJELASAN
#menggunakan split() untuk memecah teks yg menempel
1.Langkah Awalnya kan kita punya data teks panjang banget dari mesin kasir (POS) yang bentuknya nempel-nempel dan berantakan. Nah, biar gampang diolah, kita pecah dulu teks itu. Pertama, kita pakai perintah split(";") untuk misahin Transaksi 1 dan Transaksi 2. Kalau udah kepisah, masing-masing transaksi kita pecah lagi pakai split("#"). Tujuannya biar elemen-elemen di dalamnya kayak ID, NAMA, QTY, dan PRICE kepotong-potong dan masuk ke dalam daftar (list) yang terpisah nah dari sini kita bisa simpulkan jika .split() ini berfungsi untuk memcah suatu teks yg menempel

#Cleaning & Casting
2 dan 3.Setelah terpotong-potong, teksnya kan masih ada labelnya tuh, kayak tulisan "NAMA:", "QTY:", dan "PRICE:". Bagian itu kita buang pakai fungsi replace() biar sisa nilainya aja. Terus, kita pakai strip() buat nyapu bersih kalau ada spasi kosong di depan atau belakang kata biar datanya nggak error.
Khusus buat nama menu kopinya, kita pakai fungsi title() supaya otomatis huruf awalnya jadi kapital (Title Case) dan enak dibaca. Terakhir yang paling penting, karena jumlah (QTY) dan harga (PRICE) mau kita hitung pakai matematika, tipe datanya yang awalnya teks (string) wajib kita ubah jadi angka bulat pakai perintah int() atau Casting.
nah kalau masih bingung dengan replace(),strip(),title(),dan int() aku bakal jelasin singkat nih nah untuk:

replace()=fungsinya tuh mencari kata atau karakter dalam teks untuk diganti dengan kata lain.
Kesimpulan Penggunaan dalam kasus uts ini: Paling sering dipakai untuk membuang teks yang tidak perlu. Misalnya, kamu punya data "QTY:3". Kamu pakai replace("QTY:", "") untuk mengganti tulisan "QTY:" menjadi kosong, sehingga sisa angkanya aja "3".

strip()=fungsinya mengahpus spasi yang ada paling depan atau paling belakang pada teks.
penggunaan strip pada kasus uts ini bertujuan untuk pemotongan teks meninggalkan spasi di ujung-ujung kata, misalnya "  kopi susu gula aren " atau " 3 ". Spasi ini kalau dibiarkan bisa bikin laporan jadi mencong atau perhitungan error. Dengan menambahkan .strip()

title() semata-mata untuk estetika berfungsi agar awalan huruf menjadi besar dan sisanya tetap huruf krcil

int() fungsinya mengubah tipe data f-string menjadi angka bulat int(integer)
dalam kasus uts ini Komputer ngelihat angka "18000" dan "3" dari teks mesin kasir itu masih sebagai tulisan biasa (teks), bukan angka matematika. Jadi kalau dikalikan, komputernya bakal nolak/eror. Makanya, kita pakai int() untuk mengubah tulisan tersebut menjadi angka beneran (integer).

#aritmatika
4.Karena QTY dan PRICE udah berubah jadi angka, kita tinggal kaliin aja keduanya buat dapet subtotal dari masing-masing transaksi kopi. Kalau subtotal transaksi pertama dan kedua udah dapet, tinggal kita tambahin deh buat nyari Total Pendapatan hari itu.

#membuat frame tabel menggunakan ("=") dan ("-")
Biar ada garis pembatas yang panjangnya pas, kita cetak tanda sama dengan dan tanda strip lalu dikali 60 ("=" * 60).bakal otomatis nyetak garis itu sepanjang 60 karakter.

Buat judulnya biar bisa persis di tengah frame, kita pakai format ^60. Terus buat isi tabelnya, kita pakai teknik F-String Alignment nah f-string aligment ini sendiri berfungsi untuk meratakan,merapikan dan mensejajarkan teks. Tanda < di dalam kurung kurawal itu ibaratnya kita ngasih instruksi: "Tolong kasih jarak spasi sekian karakter dan ratain teksnya ke kiri". Makanya kolom MENU, QTY, HARGA, dan SUBTOTAL bisa sejajar rapi ke bawah
"""